### ISSUE TITLE
Error of certificate install during setup wizard process.  ERROR: There is no object registered under name 'gui'.

### ISSUE THREAD

**Issue by tyePhDCandy** [mysql/mysql-shell-plugins#15]
os version : windows 10 19043.1415

# Error of certificate install during setup wizard process.

## the setup wizard shows this :
**ERROR: There is no object registered under name 'gui'.**

## **Description :**
1. the certificate pop-up window which should occur during setup wizard process does not happen.
2. the error images in my vscode window shows :
![image](https://user-images.githubusercontent.com/22343659/196468710-d7d9a251-bdba-440d-920b-44c4f9644cfb.png)

**Comment by mike-lischke** [comment]
This error indicates that the GUI plugin for the shell is not installed. It should be in your home folder, in the .mysql-gui/plugins folder.

**Comment by tyePhDCandy** [comment]
@mike-lischke  thank you for your attention. 
**os** : windows 10.

**what i did and where i am** : 
* I installed latest version of mysql(8.0.31), mysql-workbench(8.0.31) using scoop. 
* I cant find mysql-gui or any gui related folder in my mysql, mysql-workbench folders. 
* i'm not sure what i did wrong.

thanks again.

**Comment by mike-lischke** [comment]
It's not necessary to install MySQL or MySQL Workbench locally. The VS Code extension is a client like MySQL Workbench and can connect to local and remote servers likewise. Most important is that you install the extension from the MS marketplace, which comes with a MySQL shell binary and installs the required plugins.

**Comment by tyePhDCandy** [comment]
thanks. i understand. I put the log message below.
The error log message is presented below.
the installation process got stuck on a init.py file, which i think is crucial for the installation of certificated.

```
2022-11-18 09:51:27: Error: Error loading Python file 'c:\Users\<my user name>\scoop\apps\vscode\1.73.1\data\extensions\oracle.mysql-shell-for-vs-code-1.5.0-win32-x64\shell\lib\mysqlsh\plugins\plugins_plugin\init.py':
	Execution failed: 
Traceback (most recent call last):
  File "init.py", line 29, in <module>
  File "c:\Users\<my user name>\scoop\apps\vscode\1.73.1\data\extensions\oracle.mysql-shell-for-vs-code-1.5.0-win32-x64\shell\lib\mysqlsh\python-packages\mysqlsh\plugin_manager\__init__.py", line 24, in <module>
    from .general import VERSION
  File "c:\Users\<my user name>\scoop\apps\vscode\1.73.1\data\extensions\oracle.mysql-shell-for-vs-code-1.5.0-win32-x64\shell\lib\mysqlsh\python-packages\mysqlsh\plugin_manager\general.py", line 26, in <module>
    import urllib.request
  File "C:\Users\<my user name>\scoop\apps\pyenv\current\pyenv-win\versions\3.9.7\Lib\urllib\request.py", line 88, in <module>
    import http.client
  File "C:\Users\<my user name>\scoop\apps\pyenv\current\pyenv-win\versions\3.9.7\Lib\http\client.py", line 71, in <module>
    import email.parser
  File "C:\Users\<my user name>\scoop\apps\pyenv\current\pyenv-win\versions\3.9.7\Lib\email\parser.py", line 12, in <module>
    from email.feedparser import FeedParser, BytesFeedParser
  File "C:\Users\<my user name>\scoop\apps\pyenv\current\pyenv-win\versions\3.9.7\Lib\email\feedparser.py", line 27, in <module>
    from email._policybase import compat32
  File "C:\Users\<my user name>\scoop\apps\pyenv\current\pyenv-win\versions\3.9.7\Lib\email\_policybase.py", line 9, in <module>
    from email.utils import _has_surrogates
  File "C:\Users\<my user name>\scoop\apps\pyenv\current\pyenv-win\versions\3.9.7\Lib\email\utils.py", line 29, in <module>
    import socket
  File "C:\Users\<my user name>\scoop\apps\pyenv\current\pyenv-win\versions\3.9.7\Lib\socket.py", line 51, in <module>
    import _socket
ImportError: DLL load failed while importing _socket: 找不到指定的模块。

2022-11-18 09:51:27: Warning: Found errors loading plugins, for more details look at the log at: C:\Users\<my user name>\AppData\Roaming\MySQL\mysqlsh-gui\mysqlsh.log
2022-11-18 09:51:27: Error: There is no object registered under name 'gui'
```

**Comment by nlgl** [comment]
Any development on the subject?

**Comment by tyePhDCandy** [comment]
negative. The problem remains unsolved. So, I switched back to mysql workbench .
________________________________
发件人: n.lgl ***@***.***>
发送时间: 2022年12月30日 19:32
收件人: mysql/mysql-shell-plugins ***@***.***>
抄送: tyeAwesome ***@***.***>; Author ***@***.***>
主题: Re: [mysql/mysql-shell-plugins] Error of certificate install during setup wizard process. ERROR: There is no object registered under name 'gui'. (Issue #15)


Any development on the subject?

―

**Comment by mike-lischke** [comment]
Sorry for the delay. That looks like your Python installation is incomplete or messed up. This error is about dependency which was not found by Python.

**Comment by rennox** [comment]
In reality that's not the case, we are also shipping python within the shell extension.

More details about your specific scenario would be helpful. The logged paths don't correspond to a normal install path, normal install path would be something like:

C:\Users\<user-name>\.vscode\extensions\oracle.mysql-shell-for-vs-code-1.7.0\shell\.....

What kind of environment is this?

**Comment by mike-lischke** [comment]
No activity here. Closing...
