### ISSUE TITLE
WSL VS Code MySQL Shell UnicodeDecodeError: 'utf-8' codec can't decode byte 0xca in position 6: invalid continuation byte

### ISSUE THREAD

**Issue by opsarno** [mysql/mysql-shell-plugins#46]
Environment
- Windows 11
- VS Code 1.87.0
- MySQL Shell for VS Code v1.14.2

```bash
# RockyLinux 8.9
PS C:\Users\fande> wsl -l -v
  NAME                   STATE           VERSION
* RockyLinux             Running         2
```

---

MySQL Shell For VS Code - Debug message
```bash
Running on a local VS Code session.
Starting embedded MySQL Shell, using config dir '/root/.mysqlsh-gui' ...
Please enter the single instance token: 
15:58:31.542697 INFO: Token read from STDIN
15:58:31.542765 INFO: Starting MySQL Shell GUI web server...

15:58:31.542928 INFO: 	Checking web server certificate...

15:58:31.659934 ERROR: Exception information:
Traceback (most recent call last):
-  File "/root/.vscode-server/extensions/oracle.mysql-shell-for-vs-code-1.14.2/shell/lib/mysqlsh/plugins/gui_plugin/core/lib/certs/locations.py", line 719, in _get_installed_certs
-    exit_code, output = lib.run_shell_cmd(cmd)
-  File "/root/.vscode-server/extensions/oracle.mysql-shell-for-vs-code-1.14.2/shell/lib/mysqlsh/plugins/gui_plugin/core/lib/SystemUtils.py", line 157, in run_shell_cmd
-    output = stream.read()
-  File "/root/.vscode-server/extensions/oracle.mysql-shell-for-vs-code-1.14.2/shell/lib/mysqlsh/lib/python3.9/codecs.py", line 322, in decode
-    (result, consumed) = self._buffer_decode(data, self.errors, final)
-UnicodeDecodeError: 'utf-8' codec can't decode byte 0xca in position 6: invalid continuation byte

15:58:31.660251 DEBUG: The certificate installation is inconsistent:
15:58:31.660286 DEBUG: USER_HOME: /root/.mysqlsh-gui/plugin_data/gui_plugin/web_certs/rootCA.crt, [Installed: True, Valid: True]
15:58:31.660304 DEBUG: WIN: WIN Certificate Store, [Installed: False, Valid: False, Reason: The certificate is not installed at WIN Certificate Store]

15:58:31.660316 INFO: The installed certificate has errors: The certificate is not installed at WIN Certificate Store

15:58:31.660362 INFO: 	Certificate is not installed. Use gui.core.installShellWebCertificate() to install one.

Starting embedded MySQL Shell, using config dir '/root/.mysqlsh-gui' ...
15:58:42.289654 ERROR: Exception information:
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xca in position 6: invalid continuation byte

15:58:46.690508 ERROR: Exception information:
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xca in position 6: invalid continuation byte

15:58:46.782888 ERROR: Exception information:
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xca in position 6: invalid continuation byte

true
```

![image](https://github.com/mysql/mysql-shell-plugins/assets/8611744/6f3ea1b8-6e56-46f1-94e8-5b1c1dabd352)

**Comment by Misaka-Mikodo** [comment]
I have the same issue.

**Comment by Misaka-Mikodo** [comment]
@opsarno I found the reason for this problem: the character set of your windows terminal is gbk encoding, so using utf-8 decoding will cause errors. I have a simple solution: open the plug-in root directory, such as `/root/.vscode-server/extensions/oracle.mysql-shell-for-vs-code-1.14.2/shell/lib/mysqlsh/plugins/gui_plugin/core/lib/SystemUtils.py` shown in your log, add `encoding='gbk'` in the `subprocess.Popen` function called by `popen` function, and restart the vscode to install it correctly.
