### ISSUE TITLE
getting error in github codespace editor

### ISSUE THREAD

**Issue by ashrafmajdee** [mysql/mysql-shell-plugins#7]
After installing the extension and running the welcome wizard, I get the following error in github codespaces editor
```
Starting embedded MySQL Shell, using config dir '/home/vscode/.mysqlsh-gui' ...
Please enter the single instance token: 
9:29:11.393005 INFO: Token read from STDIN
9:29:11.393112 INFO: Starting MySQL Shell GUI web server...


9:29:11.393418 INFO: 	Checking web server certificate...

9:29:11.446890 INFO: 	Certificate is installed.


9:29:11.529561 INFO: 	Port: 43731
9:29:11.529816 INFO: 	Secure: True
9:29:11.529915 INFO: 	Webroot: /home/vscode/.vscode-remote/extensions/oracle.mysql-shell-for-vs-code-1.3.0-linux-x64/shell/lib/mysqlsh/plugins/gui_plugin/core/webroot
9:29:11.529981 INFO: 	Mode: Single user

9:29:11.560963 INFO: Websocket connected
9:29:11.561208 INFO: Registering session...

9:29:11.594042 INFO: Sending session response...

Internal error: Error: ReferenceError: document is not defined
    at ListenerExecutor.then (/home/vscode/.vscode-remote/extensions/oracle.mysql-shell-for-vs-code-1.3.0-linux-x64/output/frontend/src/supplement/Dispatch/ListenerExecutor.js:46:35)
    at ListenerEntry.then (/home/vscode/.vscode-remote/extensions/oracle.mysql-shell-for-vs-code-1.3.0-linux-x64/output/frontend/src/supplement/Dispatch/ListenerEntry.js:97:14)
    at new ExtensionHost (/home/vscode/.vscode-remote/extensions/oracle.mysql-shell-for-vs-code-1.3.0-linux-x64/output/extension/src/ExtensionHost.js:171:30)
    at activate (/home/vscode/.vscode-remote/extensions/oracle.mysql-shell-for-vs-code-1.3.0-linux-x64/output/extension/src/extension.js:95:12)
    at Function._callActivateOptional (/vscode/bin/linux-x64/30d9c6cd9483b2cc586687151bcbcd635f373630/out/vs/workbench/api/node/extensionHostProcess.js:88:17470)
    at Function._callActivate (/vscode/bin/linux-x64/30d9c6cd9483b2cc586687151bcbcd635f373630/out/vs/workbench/api/node/extensionHostProcess.js:88:17131)
    at /vscode/bin/linux-x64/30d9c6cd9483b2cc586687151bcbcd635f373630/out/vs/workbench/api/node/extensionHostProcess.js:88:14945
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at S._activate (/vscode/bin/linux-x64/30d9c6cd9483b2cc586687151bcbcd635f373630/out/vs/workbench/api/node/extensionHostProcess.js:83:8180)
    at S._waitForDepsThenActivate (/vscode/bin/linux-x64/30d9c6cd9483b2cc586687151bcbcd635f373630/out/vs/workbench/api/node/extensionHostProcess.js:83:8122)
    at S._initialize (/vscode/bin/linux-x64/30d9c6cd9483b2cc586687151bcbcd635f373630/out/vs/workbench/api/node/extensionHostProcess.js:83:7486)

```

![Screenshot 2022-06-16 143841](https://user-images.githubusercontent.com/3441250/174042078-ffe7555e-f49d-42ec-a9c0-486e4390624a.jpg)

**Comment by mike-lischke** [comment]
A fix for this issue has been pushed for the next release. Public bug report: https://bugs.mysql.com/bug.php?id=107592
